# Generated by Django 3.0.4 on 2020-03-20 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbd',
            name='autors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorsCr', to=settings.AUTH_USER_MODEL, verbose_name='Автор обращения'),
        ),
        migrations.AddField(
            model_name='ticketbd',
            name='groups',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_aCr', to='Base.CustomGroup', verbose_name='Подразделения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbd',
            name='maneger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_aCr', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='ticketchat',
            name='name',
            field=models.ForeignKey(db_column='username', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userCreated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketchat',
            name='post',
            field=models.ForeignKey(db_column='pk', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Base.TicketBD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='Base.CustomGroup', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='HistoricalTicketBD',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_modifite', models.DateField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='Дата последнего изменения')),
                ('data_created', models.DateField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='Дата на момент создания')),
                ('title', models.CharField(max_length=50, verbose_name='Названия заявки')),
                ('content', models.TextField(verbose_name='Текст обращения')),
                ('status', models.IntegerField(choices=[(0, 'В обработке'), (1, 'Отправленно на доработку'), (2, 'В работе'), (3, 'Выполнена'), (4, 'Закрыта')], default=0, verbose_name='Статус заявки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Закрыта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autors', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор обращения')),
                ('groups', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Base.CustomGroup', verbose_name='Подразделения')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maneger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical ticket bd',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
