# Generated by Django 3.0.4 on 2020-03-21 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20200320_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticketbd',
            name='created_t',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketbd',
            name='created_t',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
