# Generated by Django 3.0.4 on 2020-03-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20200319_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_modifite', models.DateField(auto_created=True, auto_now=True, db_index=True, verbose_name='Дата последнего изменения')),
                ('data_created', models.DateField(auto_created=True, auto_now_add=True, db_index=True, verbose_name='Дата на момент создания')),
                ('title', models.CharField(max_length=50, verbose_name='Названия заявки')),
                ('content', models.TextField(verbose_name='Текст обращения')),
                ('status', models.IntegerField(choices=[(0, 'В обработке'), (1, 'Отправленно на доработку'), (2, 'В работе'), (3, 'Выполнена'), (4, 'Закрыта')], default=0, verbose_name='Статус заявки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('autors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorsCr', to=settings.AUTH_USER_MODEL, verbose_name='Автор обращения')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_aCr', to='Base.CustomGroup', verbose_name='Подразделения')),
                ('maneger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_aCr', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
        ),
    ]
