# Generated by Django 3.0.4 on 2020-03-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_auto_20200321_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketbd',
            options={'ordering': ('created_t',)},
        ),
    ]
