# Generated by Django 3.0.4 on 2020-03-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_ticketbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, related_name='userCreated', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(db_column='pk', on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Base.TicketBD')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
