# Generated by Django 3.0.4 on 2020-03-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_auto_20200321_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticketbd',
            name='groups',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Base.CustomGroup', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='ticketbd',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_aCr', to='Base.CustomGroup', verbose_name='Отдел'),
        ),
    ]
