# Generated by Django 3.0.4 on 2020-03-20 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_ticketchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbd',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Закрыта'),
        ),
        migrations.CreateModel(
            name='HistoricalTicketBD',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_modifite', models.DateField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='Дата последнего изменения')),
                ('data_created', models.DateField(auto_created=True, blank=True, db_index=True, editable=False, verbose_name='Дата на момент создания')),
                ('title', models.CharField(max_length=50, verbose_name='Названия заявки')),
                ('content', models.TextField(verbose_name='Текст обращения')),
                ('status', models.IntegerField(choices=[(0, 'В обработке'), (1, 'Отправленно на доработку'), (2, 'В работе'), (3, 'Выполнена'), (4, 'Закрыта')], default=0, verbose_name='Статус заявки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Закрыта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autors', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор обращения')),
                ('groups', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Base.CustomGroup', verbose_name='Подразделения')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maneger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical ticket bd',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
