# Generated by Django 3.0.4 on 2020-03-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_auto_20200320_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbd',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_aCr', to='Base.CustomGroup', verbose_name='Подразделения'),
        ),
    ]
